version: 2
updates:
  # Maintain dependencies for Composer (PHP)
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(deps)'

  # Maintain dependencies for npm (Node.js)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(deps)'

  # Maintain versions for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore(deps)'
